language: node_js

node_js:
  - "8"
install:
  - npm install
  - npm update

cache: node_modules

script: 'true'

before_deploy:
  - rm -rf www/ || true
  - tsc
  - mkdir www/tmp
  - cp package.json ./www/package.json
  - ls -la www
  - cd www && zip -r node-server.zip .

after_deploy:
  - rm -rf .tmp
  - rm -rf .DS_Store
  - rm -rf node_modules
  - rm node-server.zip
  - echo "done deploying"


deploy:
    provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRET_ACCESS_KEY_NODE
    zip-file: node-server.zip
    region: "us-west-2"
    skip_cleanup: true
    app: "spotted-dev"
    env: "spotted-dev-dev"
    bucket_name: "elasticbeanstalk-us-west-2-169203564268"
    bucket_path: "spotted-dev"

    on:
      branch: master