language: node_js

node_js:
  - "10"
install:
  - npm install
  - npm update

cache: node_modules

script: 'true'

before_deploy:
  - npm run build
  # - rm -rf frontend
  # - rm -rf build-backend/ || true
  # - tsc
  # - mkdir build-backend/tmp
  # - cp package.json ./build-backend/package.json
  # - cp .npmrc build-backend/.npmrc 
  # - ls -la build-backend
  # - cd build-backend && zip -r node-server.zip .

after_deploy:
  - rm -rf .tmp
  - rm -rf .DS_Store
  - rm -rf node_modules
  - rm node-server.zip
  - echo "done deploying"

deploy:
    provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRET_ACCESS_KEY_NODE
    zip-file: build-backend/Archive.zip
    region: "us-west-2"
    skip_cleanup: true
    app: "spotted-dev"
    env: "spotted-dev-dev"
    bucket_name: "elasticbeanstalk-us-west-2-169203564268"
    bucket_path: "spotted-dev"
    on:
      branch: master